### ISSUE TITLE
JSFiddle examples display /* EOS */ above the demo.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/docs#116]
The JSFiddle examples display `/* EOS */` above the Handsontable instance. I think it might be caused by our `<!-- Ugly Hack due to jsFiddle issue -->`.

We might have to rewrite our "edit in jsfiddle" logic to utilize the "resources" section of JSFiddle.

**Comment by jansiegel** [comment]
I did some research, and it seems the issue is fixable within an hour or so (I think I got it working in about ~30minutes - obviously it would need some additional testing).

The thing is, my "fix" consists only of moving the resources to the "resources" section of JSFiddle and removing them from the CSS section. Unfortunately, the entire `samples.js` file is pretty messy - it lacks any structure, contains some logic required for Handsontable Pro, which we no longer need, and generally is in dire need of refactoring.

I think migration to `8.0` is a good time to take care of that as well. It would, obviously take more time (I'd say about a day, to understand what's going on there and rewrite the entire thing - maybe a couple of hours more to test it thoroughly.

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/docs/issues/111

**Comment by aninde** [comment]
Adding resources into HTML section instead of CSS or "official" resources fix this issue https://jsfiddle.net/aninde/07daewnL/.
The HTML5 specification allows adding a link tag to the html https://www.w3.org/TR/html52/links.html#body-ok

<img width="784" alt="Screenshot 2021-01-11 at 12 39 45" src="https://user-images.githubusercontent.com/30186818/104178123-1bef3600-540a-11eb-98cb-aac27e2ea99f.png">

**Comment by swistach** [comment]
We have changed this. In the new documentation, we use external scripts and links to the HTML section.
