### ISSUE TITLE
Example > Sport Sorting Bug

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#23]
Bug at: [`Example > Sport `](http://handsontable.com/examples.html?_ga=1.131382479.1318855413.1438118741#fndtn-sport)

To reproduce: 
sort few times an income column.

Result: 
after few clicks only two first rows get sorted.

**Comment by Rolok** [comment]
There aren't that many (29) columns in the sporting example.  The issue seems to manifest itself as soon as you attempt to sort when the window is scrolled so that the first column is completely off screen.  If it is still even partially onscreen it works.  For example, on http://jsfiddle.net/hdpL3Lnr/4/  While Column A is on the screen, sorting on column C works fine.  As soon as the view is scrolled horizontally so that Column A is no longer on the screen, the sorting on column C will start to sort only the first two rows after 3 sorts on it.

**Comment by AMBudnik** [comment]
Thanks for investigating @Rolok

**Comment by AMBudnik** [comment]
demo no longer available.
