### ISSUE TITLE
Add missing information about rowHeaders and colHeaders

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs#66]
The `rowHeaders` is said to accept 
![image](https://user-images.githubusercontent.com/10757813/62046374-0b440380-b208-11e9-944b-09c4d62c890c.png)
![image](https://user-images.githubusercontent.com/10757813/62046399-18f98900-b208-11e9-8fcb-a83b4e7fbebf.png)

Boolean, string/s or an array of strings. However, it also works for numbers (single number, an array of numbers and a function returning numbers).

```js
rowHeaders: function(col){
	return col * 10
}
```
![image](https://user-images.githubusercontent.com/10757813/62046499-59f19d80-b208-11e9-80b1-54ec2f4d332d.png)

**Comment by AMBudnik** [comment]
It also applies to `colHeaders`.

**Comment by swistach** [comment]
It happens because it is the default behaviour of the `Number.toString()` method. You can read more here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString#description.

It's a similar case to https://github.com/handsontable/docs/issues/64. In my opinion, we should keep the precise list of supported types that we expect to receive that are required to work stable.
